services:
    App\Ecommerce\IndexService\Config\MySqlConfig:
        parent: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\AbstractConfig

pimcore_ecommerce_framework:
  index_service:
    tenants:
      default:
        config_id: 'App\Ecommerce\IndexService\Config\MySqlConfig'
        search_attributes:
          - name
          - description
        attributes:
          name:
            fieldname: name
            type: varchar(255)
            filter_group: string
          description:
            fieldname: description
            type: varchar(255)
            filter_group: string
          price:
            fieldname: price
            type: double
            filter_group: double


  filter_service:
        tenants:
            default:
                filter_types:
                    FilterInputfield:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Input
                        template: 'filters/input.html.twig'
                    FilterNumberRange:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRange
                        template: 'filters/numberrange.html.twig'
                    FilterNumberRangeSelection:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRangeSelection
                        template: 'filters/numberrange_select.html.twig'
                    FilterSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Select
                        template: 'filters/select.html.twig'
                    FilterSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectFromMultiSelect
                        template: 'filters/select.html.twig'
                    FilterMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelect
                        template: 'filters/multi_select.html.twig'
                    FilterMultiSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelectFromMultiSelect
                        template: 'filters/multi_select.html.twig'
                    FilterMultiRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelectRelation
                        template: 'filters/multi_relation.html.twig'
                    FilterCategory:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectCategory
                        template: 'filters/select_category.html.twig'
                    FilterRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectRelation
                        template: 'filters/object_relation.html.twig'

