services:
    App\Ecommerce\IndexService\Config\MySqlConfig:
        parent: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\AbstractConfig

pimcore_ecommerce_framework:
  index_service:
    tenants:
      default:
        config_id: 'App\Ecommerce\IndexService\Config\MySqlConfig'
        search_attributes:
          - name
          - description

        attributes:
          name:
            fieldname: name
            type: varchar(255)
            filter_group: string
          description:
            fieldname: description
            type: varchar(255)
            filter_group: string
          price:
            fieldname: price
            type: double
            filter_group: double
          productType:
            interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\DefaultObjects
            filter_group: relation
          localization:
            interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\DefaultObjects
            filter_group: relation


  filter_service:
        tenants:
            default:
                filter_types:
                    FilterInputfield:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Input
                        template: 'filters/input.html.twig'
                    FilterNumberRange:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRange
                        template: 'filters/numberrange.html.twig'
                    FilterNumberRangeSelection:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRangeSelection
                        template: 'filters/numberrange_select.html.twig'
                    FilterSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Select
                        template: 'filters/select.html.twig'
                    FilterSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectFromMultiSelect
                        template: 'filters/select.html.twig'
                    FilterMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelect
                        template: 'filters/multi_select.html.twig'
                    FilterMultiSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelectFromMultiSelect
                        template: 'filters/multi_select.html.twig'
                    FilterMultiRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelectRelation
                        template: 'filters/multi_relation.html.twig'
                    FilterCategory:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectCategory
                        template: 'filters/select_category.html.twig'
                    FilterRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectRelation
                        template: 'filters/object_relation.html.twig'

  cart_manager:
    tenants:
      # defaults for all cart managers
      _defaults:
      # define service manager id of cart service - following value is default and can be omitted
        cart_manager_id: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\MultiCartManager
          # configuration for carts - the following values are set by default and can be omitted 
          cart:
            # service ID of a cart factory which creates individual carts at runtime                    
            factory_id: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\CartFactory
            
            # options passed to cart factory, e.g. the cart class (available options vary by factory implementation)
            factory_options:
                cart_class_name: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\Cart
                guest_cart_class_name: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\SessionCart

      default:   
        

      # additional checkout tenant for cart manager
      #  - active tenant is set at \Pimcore\Bundle\EcommerceFrameworkBundle\EnvironmentInterface::setCurrentCheckoutTenant()
      noShipping: ~ # inherits from _defaults

  checkout_manager:
    tenants:
      # _defaults:
        # the following two values are default values an can be omitted
        # service ID of a checkout manager factory which builds cart specific checkout managers
        # factory_id: Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\CheckoutManagerFactory
              
        # # # options passed to the factory - available options vary by implementation
        # factory_options:
        #   class: \Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\CheckoutManager
        #   handle_pending_payments_strategy: Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\HandlePendingPayments\CancelPaymentOrRecreateOrderStrategy

        # # commit order processor
        # commit_order_processor:
        #   # order processor service ID
        #   id: Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\CommitOrderProcessor
                  
        #     # options passed to the commit order processor - available options vary by implementation
        #     options:
        #       confirmation_mail: /en/emails/order-confirmation
      default:
        payment:
          provider: paypal
        steps:
          deliveryaddress:
            class: \Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\DeliveryAddress
          confirm:
            class: \App\Ecommerce\CheckoutManager\Confirm


  order_manager:
    tenants:
      default:
        options:
          parent_order_folder: /Shop/Orders/%%Y/%%m/%%d
  
  
  payment_manager:
    #payment_manager_id: Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\PaymentManager
    providers:
      paypal:
        provider_id: Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\PayPalSmartPaymentButton
        profile: sandbox
        profiles:
          sandbox:
            client_id: 'AWZqIhnCwX4TarxqWeJnhnsiwbzEf0h34zxW45GQKK_peQ5c0zzA-4HVo_2_ePMeGfItyX8EFO_gWhc_'
            client_secret: 'EPDQNlp_8KiADVFGppsFGGm6wQy81iAqAkYU6300PWaPMNUGPMpd3myyN9ET8VLUAJsbVMFz9Uek1OPS'

            # defines, if payment caputure should take place automatic or manual, default is automatic
            capture_strategy: automatic

            # defines mode of PayPal API, default value is sandbox
            mode: sandbox

            # defines PayPal application context for shipping, default value is NO_SHIPPING
            # see https://developer.paypal.com/docs/api/orders/v2/#definition-application_context
            shipping_preference: NO_SHIPPING

            # defines PayPal application context for user action, default value is PAY_NOW
            # see https://developer.paypal.com/docs/api/orders/v2/#definition-application_context
            user_action: PAY_NOW